name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true
    - name: Setup Hugo
      uses: ./.github/actions/actions-hugo
      with:
          hugo-version: 'latest'
    - name: Clean public directory
      run: rm -rf public
    - name: Build
      run: hugo --theme=m10c
    - name: Deploy
      uses: ./.github/actions/actions-gh-pages
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
